import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryContext from "@/context/ReactQueryContext";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <header className="border-b">
          <div className="max-w-screen-xl mx-auto px-6 ">
            <Navbar />
          </div>
        </header>
        <main className="max-w-screen-lg mx-auto px-6 ">
          <ReactQueryContext>{children}</ReactQueryContext>
        </main>
      </body>
    </html>
  );
}
